# GCP Cloud SQL Connection
spring.cloud.gcp.sql.database-name=expenses
spring.cloud.gcp.sql.instance-connection-name=kishorsurya2011-org:us-central1:expense-db-instance

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
